name: "Docker Push Deploy"
description: "Docker push action to AWS ECR and deploy with CF"

inputs:
  aws-access-key-id:
    description: "The AWS access key id to identify the action"
    required: true

  aws-secret-access-key:
    description: "The AWS secret access key to identify the action"
    required: true

  aws-region:
    description: "The AWS region to deploy the service to"
    required: false
    default: "us-east-1"
    
  aws-account:
    description: "AWS account number that holds the repository"
    required: true

  app-name:
    description: "Container name that will be used to be deployed"
    required: true

  app-port:
    description: "Application port"
    required: false
    default: "8000"

  stage:
    description: "Application stage"
    required: true
    default: "dev"

  tag:
    description: "New tag for docker image"
    required: false

  stack-file:
    description: "Relative pat to the CF stack file for the deployment"
    required: true
    default: "stackcf.yml"

  cluster:
    description: "ECS Cluster name to deploy the container"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup AWS Cli
      run: sh ${{ github.action_path }}/../common/awscli-setup.sh
      shell: bash

    - name: Setup Docker
      run: sh ${{ github.action_path }}/../common/docker-setup.sh
      shell: bash

    - name: Build image
      run: |
        sh ${{ github.action_path }}/../common/docker/build.sh \
          ${{ inputs.stage }} \
          ${{ inputs.app-name }} \
          ${{ inputs.app-port }} \
          ${{ inputs.aws-access-key-id }} \
          ${{ inputs.aws-region }} \
          ${{ inputs.aws-secret-access-key }}
      shell: bash

    - name: Push image
      run: |
        sh ${{ github.action_path }}/../common/docker/push.sh \
          ${{ inputs.tag }} \
          ${{ inputs.app-name }} \
          ${{ inputs.aws-account }} \
          ${{ inputs.aws-access-key-id }} \
          ${{ inputs.aws-secret-access-key }} \
          ${{ inputs.aws-region }}
      shell: bash

    - name: Deploy with CF
      run: |
        sh ${{ github.action_path }}/../common/docker/deploy.sh \
          "${{ github.action_path }}/${{ inputs.stack-file }}" \
          ${{ inputs.tag }} \
          ${{ inputs.app-name }} \
          ${{ inputs.app-port }} \
          ${{ inputs.aws-account }} \
          ${{ inputs.cluster }} \
          ${{ inputs.aws-access-key-id }} \
          ${{ inputs.aws-secret-access-key }} \
          ${{ inputs.aws-region }}
      shell: bash
